default:
  navigation:
    - title: Женщинам
      subtitle: Категории
      url: /categories/women
      items:
        - :title: Юбки
          :url: /categories/women/skirts
        - :title: Платья
          :url: /categories/women/dresses
        - :title: Рубашки и Блузки
          :url: /categories/women/shirts-and-blouses
        - :title: Свитеры
          :url: /categories/women/sweaters
        - :title: Топы и футболки
          :url: /categories/women/tops-and-t-shirts
        - :title: Куртки и пальто
          :url: /categories/women/jackets-and-coats
      promo_banners:
        - subtitle: Новая коллекция
          title: Summer 2019
          url: /categories/new-collection/summer-2019
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /categories/special-offers/30-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Мужчинам
      subtitle: Категории
      url: /categories/men
      items:
        - :title: Рубашки
          :url: /categories/men/shirts
        - :title: Футболки
          :url: /categories/men/t-shirts
        - :title: Свитеры
          :url: /men/categories/sweaters
        - :title: Куртки и пальто
          :url: /t/categories/men/jackets-and-coats
      promo_banners:
        - subtitle: Новая коллекция
          title: Summer 2019
          url: /categories/new-collection/summer-2019
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /categories/special-offers/30-off
          image: 'meganav/promo_banner_right-second-category.jpg'
    - title: Спортивная одежда
      subtitle: Категории
      url: /categories/sportswear
      items:
        - :title: Верх
          :url: /categories/sportswear/tops
        - :title: Толстовки
          :url: /categories/sportswear/sweatshirts
        - :title: Штаны
          :url: /categories/sportswear/pants
      promo_banners:
        - subtitle: Новая коллекция
          title: Лето 2021
          url: /categories/new-collection/summer-2021
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /categories/special-offers/30-off
          image: 'meganav/promo_banner_right-third-category.jpg'
